// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace GraduationProject_API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230425110708_AddedMoreConfigurationData")]
    partial class AddedMoreConfigurationData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84796c48-d538-4954-a98a-622dc5c9325a"),
                            Description = "The Computer Science Department at Damanhour University is a vibrant academic community dedicated to advancing knowledge and technology in the field of computer science. The department offers a range of undergraduate and graduate programs that provide students with a solid foundation in computer science theory and practical skills.",
                            FacultyId = new Guid("d0552b49-6e7d-4ced-8a30-62ce8066a2d4"),
                            Name = "Computer Science",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("794da9eb-b65e-45ba-a9dd-caa9a22c7d40"),
                            Description = "The Information Technology (IT) Department at Damanhour University is a dynamic and innovative academic community dedicated to advancing the field of information technology through teaching, research, and service. The department offers a range of undergraduate and graduate programs that provide students with a comprehensive understanding of the theory and practice of IT.",
                            FacultyId = new Guid("d0552b49-6e7d-4ced-8a30-62ce8066a2d4"),
                            Name = "Information Technology",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("72b983a8-6386-498d-a114-0e241e7eeae0"),
                            Description = "The Information Systems (IS) Department at Damanhour University is a forward-thinking and innovative academic community dedicated to advancing the field of information systems through teaching, research, and service. The department offers a range of undergraduate and graduate programs that provide students with a comprehensive understanding of the theory and practice of information systems.",
                            FacultyId = new Guid("d0552b49-6e7d-4ced-8a30-62ce8066a2d4"),
                            Name = "Information System",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("c65f6c7f-32f7-4797-a85b-92c9ba20ecb1"),
                            Description = "The Multimedia Department at Damanhour University is a dynamic and creative academic community dedicated to advancing the field of multimedia through teaching, research, and service. The department offers a range of undergraduate and graduate programs that provide students with a solid foundation in multimedia theory and practical skills.",
                            FacultyId = new Guid("d0552b49-6e7d-4ced-8a30-62ce8066a2d4"),
                            Name = "Multimedia",
                            Rate = 0.0
                        });
                });

            modelBuilder.Entity("Entities.Models.DepartmentAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UniveristyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UniveristyId");

                    b.ToTable("DepartmentAdmins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a369173-1e2f-491f-874f-7b324c034bc2"),
                            DepartmentId = new Guid("84796c48-d538-4954-a98a-622dc5c9325a"),
                            FacultyId = new Guid("d0552b49-6e7d-4ced-8a30-62ce8066a2d4"),
                            UniveristyId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        });
                });

            modelBuilder.Entity("Entities.Models.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FacultyId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0552b49-6e7d-4ced-8a30-62ce8066a2d4"),
                            Description = "We believe that software and information technology is the future, hence we have recruited our knowledge in the fields of information system and automation.",
                            Name = "Faculty Of Computer Science and Information Technology",
                            Rate = 0.0,
                            UniversityId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        },
                        new
                        {
                            Id = new Guid("2694c80b-f092-4975-9688-5565cf1e67fc"),
                            Description = "The Faculty of Science at Damanhour University is a renowned academic institution located in the city of Damanhour, Egypt. The faculty is dedicated to providing students with a comprehensive education in the field of science, preparing them for successful careers in research, academia, and industry.",
                            Name = "Faculty Of Science",
                            Rate = 0.0,
                            UniversityId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        },
                        new
                        {
                            Id = new Guid("0f3b208b-2006-4c07-878f-27e4dd1cc99e"),
                            Description = "The Faculty of Engineering at Damanhour University is a prestigious academic institution located in the city of Damanhour, Egypt. The faculty is dedicated to providing students with a comprehensive education in the field of engineering, preparing them for successful careers in research, academia, and industry.",
                            Name = "Faculty Of Engineering",
                            Rate = 0.0,
                            UniversityId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        },
                        new
                        {
                            Id = new Guid("fafbc1d0-d161-4f1e-9ef6-f7cfd23d97f5"),
                            Description = "The Faculty of Commerce at Damanhour University is a leading academic institution located in the city of Damanhour, Egypt. The faculty is committed to providing high-quality education and training to students in the field of commerce and business.",
                            Name = "Faculty Of Commerce",
                            Rate = 0.0,
                            UniversityId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        });
                });

            modelBuilder.Entity("Entities.Models.FacultyAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UniveristyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UniveristyId");

                    b.ToTable("FacultyAdmins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69e0e900-6de2-45e8-85ca-583b32c5c5aa"),
                            FacultyId = new Guid("d0552b49-6e7d-4ced-8a30-62ce8066a2d4"),
                            UniveristyId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        });
                });

            modelBuilder.Entity("Entities.Models.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<Guid>("UniveristyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UniveristyId");

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fdc74ef3-1e3d-4a13-9f19-4e381ce4c3d2"),
                            DepartmentId = new Guid("84796c48-d538-4954-a98a-622dc5c9325a"),
                            FacultyId = new Guid("d0552b49-6e7d-4ced-8a30-62ce8066a2d4"),
                            Rate = 0.0,
                            UniveristyId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        });
                });

            modelBuilder.Entity("Entities.Models.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuestionnaireId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("Entities.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SubjectId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40504bb7-1148-4e05-ba84-2a81ffc3b918"),
                            Code = "CS311",
                            DepartmentId = new Guid("84796c48-d538-4954-a98a-622dc5c9325a"),
                            Description = "Parallel computing is a subject that focuses on the design and implementation of computing systems that are capable of performing multiple tasks simultaneously. This subject is offered in Damanhour University's Faculty of Computer Science and Information Technology, specifically within the Computer Science Department.",
                            Name = "Parallel Computing",
                            ProfessorId = new Guid("fdc74ef3-1e3d-4a13-9f19-4e381ce4c3d2"),
                            Rate = 0.0
                        });
                });

            modelBuilder.Entity("Entities.Models.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4"),
                            Description = "Damanhour University is a competitive institution in the domain of learning and pure scientific research which aims to build a learning society and to create knowledge.",
                            Name = "Damanhour University",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("e8c82519-d0c8-4c34-8cc7-a2e819644537"),
                            Description = "Alexandria University is a public university in Alexandria, Egypt. It was established in 1938 as a satellite of Fouad University, becoming an independent entity in 1942. It was known as Farouk University until after the Egyptian Revolution of 1952, when its name was changed to the University of Alexandria.",
                            Name = "Alexandria University",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("0102ff47-f01d-4614-8300-e9b9e1aad19b"),
                            Description = "Kafr El Sheikh University is an Egyptian university established in 2006, located at Kafr El Sheikh, in the middle of the Nile Delta.",
                            Name = "Kafr El Sheikh University",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("de1307a8-d751-402a-b649-4ffeabb70ac2"),
                            Description = "Tanta University is an Egyptian university in the city of Tanta, Al Gharbiyah governorate, Egypt. The university is under the direct scientific supervision of the Ministry of Higher Education.",
                            Name = "Tanta University",
                            Rate = 0.0
                        });
                });

            modelBuilder.Entity("Entities.Models.UniversityAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("UniversityAdmins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99328045-8ecf-40a1-9f0b-0dea6398f09a"),
                            UniversityId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "99328045-8ECF-40A1-9F0B-0DEA6398F09A",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "75dad6c4-43ce-412c-b4f4-e3f104ecc0fb",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEKdKXIWCPaaD6QuXSqD78GbzjkObleviPj2Uug1CPGSrjolrJ0Me3seL46fyfbHiw==",
                            PhoneNumber = "01239931230",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "818f3563-a3f3-4fff-9cb7-437a287ebac7",
                            TwoFactorEnabled = false,
                            UserName = "john.doe@example.com"
                        },
                        new
                        {
                            Id = "69E0E900-6DE2-45E8-85CA-583B32C5C5AA",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "886699f2-b0c3-48f2-ab86-b72ba22dd19e",
                            Email = "jane.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JANE.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEG8brrSWYdXl1HPtJ0joQxW1v0a28miXoGqfgARfWPac+Mqotpj9h0vb4yWC9Vc+2A==",
                            PhoneNumber = "01203993009",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dc23656a-b0aa-4f61-89de-b15519f450a1",
                            TwoFactorEnabled = false,
                            UserName = "jane.doe@example.com"
                        },
                        new
                        {
                            Id = "7A369173-1E2F-491F-874F-7B324C034BC2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "29ac8f92-99eb-455c-b7b7-7ab720e630db",
                            Email = "bob.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "Bob",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "BOB.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEL0hmY2CJfojig4iHqPqnkKjwiZ7+mtK56ORlVRJwRTyMZf6ScXnYaUa4FIuoDrrwQ==",
                            PhoneNumber = "011234356789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3cb99e36-df81-4659-9837-7432b0470368",
                            TwoFactorEnabled = false,
                            UserName = "bob.smith@example.com"
                        },
                        new
                        {
                            Id = "FDC74EF3-1E3D-4A13-9F19-4E381CE4C3D2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6ee6d756-1fba-4a69-b79e-69393d8d4d02",
                            Email = "sara.jones@example.com",
                            EmailConfirmed = true,
                            FirstName = "Sara",
                            LastName = "Jones",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA.JONES@EXAMPLE.COM",
                            NormalizedUserName = "SARA.JONES@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFUF9OhOR8ZOwbNk+HgGbX4kvQZNWYIQM7ZxZAhIII4cRAkmTK3kul6B2uWLXpA9zA==",
                            PhoneNumber = "010765432231",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "59162b5c-0c13-47f4-b21d-63e140bbc396",
                            TwoFactorEnabled = false,
                            UserName = "sara.jones@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "BEA713C7-93D2-4F39-8DC8-18F2F3070779",
                            ConcurrencyStamp = "b5c81ecf-ebe4-425b-9400-0093723ee82e",
                            Name = "University Admin",
                            NormalizedName = "UNIVERSITY ADMIN"
                        },
                        new
                        {
                            Id = "A2523A70-57E3-4B69-A405-F9752517ED62",
                            ConcurrencyStamp = "361068dc-779b-4ddf-a825-7e0667f8e597",
                            Name = "Faculty Admin",
                            NormalizedName = "FACULTY ADMIN"
                        },
                        new
                        {
                            Id = "64F2143D-B896-4355-90D2-AFD22424B234",
                            ConcurrencyStamp = "77ce8e21-e632-4e15-987d-4eb14a24be3a",
                            Name = "Department Admin",
                            NormalizedName = "DEPARTMENT ADMIN"
                        },
                        new
                        {
                            Id = "E5E3E33B-D9F2-4E95-9CEB-26F28A0028E7",
                            ConcurrencyStamp = "396bb4d6-b5f5-44a5-8c6e-9d862e36806c",
                            Name = "Professor",
                            NormalizedName = "PROFESSOR"
                        },
                        new
                        {
                            Id = "E26639C4-7023-4878-A497-FC4B12CFA272",
                            ConcurrencyStamp = "7928ff6c-e767-4548-b8a9-1e6cde8a1134",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "99328045-8ECF-40A1-9F0B-0DEA6398F09A",
                            RoleId = "BEA713C7-93D2-4F39-8DC8-18F2F3070779"
                        },
                        new
                        {
                            UserId = "69E0E900-6DE2-45E8-85CA-583B32C5C5AA",
                            RoleId = "A2523A70-57E3-4B69-A405-F9752517ED62"
                        },
                        new
                        {
                            UserId = "7A369173-1E2F-491F-874F-7B324C034BC2",
                            RoleId = "64F2143D-B896-4355-90D2-AFD22424B234"
                        },
                        new
                        {
                            UserId = "FDC74EF3-1E3D-4A13-9F19-4E381CE4C3D2",
                            RoleId = "E5E3E33B-D9F2-4E95-9CEB-26F28A0028E7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Department", b =>
                {
                    b.HasOne("Entities.Models.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Entities.Models.DepartmentAdmin", b =>
                {
                    b.HasOne("Entities.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniveristyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Faculty");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Entities.Models.Faculty", b =>
                {
                    b.HasOne("Entities.Models.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("Entities.Models.FacultyAdmin", b =>
                {
                    b.HasOne("Entities.Models.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniveristyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Entities.Models.Professor", b =>
                {
                    b.HasOne("Entities.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniveristyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Faculty");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Entities.Models.Questionnaire", b =>
                {
                    b.HasOne("Entities.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Entities.Models.Subject", b =>
                {
                    b.HasOne("Entities.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Professor", "Professor")
                        .WithMany("Subjects")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Entities.Models.UniversityAdmin", b =>
                {
                    b.HasOne("Entities.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Faculty", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Entities.Models.Professor", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Entities.Models.University", b =>
                {
                    b.Navigation("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
