// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace GraduationProject_API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230323191913_AddedFacultyTbWithInitialData")]
    partial class AddedFacultyTbWithInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FacultyId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0552b49-6e7d-4ced-8a30-62ce8066a2d4"),
                            Description = "We believe that software and information technology is the future, hence we have recruited our knowledge in the fields of information system and automation.",
                            Name = "Faculty Of Computer Science and Information Technology",
                            UniversityId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        },
                        new
                        {
                            Id = new Guid("2694c80b-f092-4975-9688-5565cf1e67fc"),
                            Description = "The Faculty of Science at Damanhour University is a renowned academic institution located in the city of Damanhour, Egypt. The faculty is dedicated to providing students with a comprehensive education in the field of science, preparing them for successful careers in research, academia, and industry.",
                            Name = "Faculty Of Science",
                            UniversityId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        },
                        new
                        {
                            Id = new Guid("0f3b208b-2006-4c07-878f-27e4dd1cc99e"),
                            Description = "The Faculty of Engineering at Damanhour University is a prestigious academic institution located in the city of Damanhour, Egypt. The faculty is dedicated to providing students with a comprehensive education in the field of engineering, preparing them for successful careers in research, academia, and industry.",
                            Name = "Faculty Of Engineering",
                            UniversityId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        },
                        new
                        {
                            Id = new Guid("fafbc1d0-d161-4f1e-9ef6-f7cfd23d97f5"),
                            Description = "The Faculty of Commerce at Damanhour University is a leading academic institution located in the city of Damanhour, Egypt. The faculty is committed to providing high-quality education and training to students in the field of commerce and business.",
                            Name = "Faculty Of Commerce",
                            UniversityId = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4")
                        });
                });

            modelBuilder.Entity("Entities.Models.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4"),
                            Description = "Damanhour University is a competitive institution in the domain of learning and pure scientific research which aims to build a learning society and to create knowledge.",
                            Name = "Damanhour University",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("e8c82519-d0c8-4c34-8cc7-a2e819644537"),
                            Description = "Alexandria University is a public university in Alexandria, Egypt. It was established in 1938 as a satellite of Fouad University, becoming an independent entity in 1942. It was known as Farouk University until after the Egyptian Revolution of 1952, when its name was changed to the University of Alexandria.",
                            Name = "Alexandria University",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("0102ff47-f01d-4614-8300-e9b9e1aad19b"),
                            Description = "Kafr El Sheikh University is an Egyptian university established in 2006, located at Kafr El Sheikh, in the middle of the Nile Delta.",
                            Name = "Kafr El Sheikh University",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("de1307a8-d751-402a-b649-4ffeabb70ac2"),
                            Description = "Tanta University is an Egyptian university in the city of Tanta, Al Gharbiyah governorate, Egypt. The university is under the direct scientific supervision of the Ministry of Higher Education.",
                            Name = "Tanta University",
                            Rate = 0.0
                        });
                });

            modelBuilder.Entity("Entities.Models.Faculty", b =>
                {
                    b.HasOne("Entities.Models.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("Entities.Models.University", b =>
                {
                    b.Navigation("Faculties");
                });
#pragma warning restore 612, 618
        }
    }
}
