// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace GraduationProject_API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230320154123_InitialDataForUniversity")]
    partial class InitialDataForUniversity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86f697d4-a762-44d6-8322-2c08c66f94e4"),
                            Description = "Damanhour University is a competitive institution in the domain of learning and pure scientific research which aims to build a learning society and to create knowledge.",
                            Name = "Damanhour University",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("e8c82519-d0c8-4c34-8cc7-a2e819644537"),
                            Description = "Alexandria University is a public university in Alexandria, Egypt. It was established in 1938 as a satellite of Fouad University, becoming an independent entity in 1942. It was known as Farouk University until after the Egyptian Revolution of 1952, when its name was changed to the University of Alexandria.",
                            Name = "Alexandria University",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("0102ff47-f01d-4614-8300-e9b9e1aad19b"),
                            Description = "Kafr El Sheikh University is an Egyptian university established in 2006, located at Kafr El Sheikh, in the middle of the Nile Delta.",
                            Name = "Kafr El Sheikh University",
                            Rate = 0.0
                        },
                        new
                        {
                            Id = new Guid("de1307a8-d751-402a-b649-4ffeabb70ac2"),
                            Description = "Tanta University is an Egyptian university in the city of Tanta, Al Gharbiyah governorate, Egypt. The university is under the direct scientific supervision of the Ministry of Higher Education.",
                            Name = "Tanta University",
                            Rate = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
